### ISSUE TITLE
[Bug]: `fluvio cluster start` should fail if a local cluster already exists

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#824] opened 2021-02-26 17:07 UTC
**What happened**
When starting a local cluster, `fluvio cluster start --local` will fail if it detects that a cluster is already installed on Minikube. However, the opposite is not true. When starting a minikube cluster, it does not check whether a local cluster is already installed. This allows users to create two clusters at once, which causes bugs because the two clusters are using the same Minikube object store for cluster object storage. This has led to a bug where a topic created in a local cluster appears visible in the minikube cluster.

**Expected behavior**
When creating a Fluvio cluster on Minikube, I expect that it should only succeed if there does not exist any other Fluvio cluster, either local or on minikube.

**Describe the setup**
- Fluvio on local and minikube
- What version of Fluvio are you using? `fluvio version`

```
$ fluvio version
Fluvio CLI        : 0.7.0
Fluvio CLI SHA256 : ba6a3f659080446d5951fb1e1906f0aebef35c83bd797515a4b734ee53acfd24
Fluvio Platform   : 0.7.0 (minikube)
Git Commit        : f4cf81b52dbd000cd6fc87b59927aeb73e737d8a
OS Details        : Darwin 10.16 (kernel 20.3.0)
```

**How to reproduce it (as minimally and precisely as possible)**
1) Run `fluvio cluster start --local`
2) Run `fluvio cluster start`
3) See that both clusters successfully are provisioned

**Environment (please complete the following information):**
 - OS: Mac Big Sur
 - Fluvio Version: 0.7.0
 - Minikube version (if used): 1.17.1
 - Kubernetes version: use `kubectl version`

```
$ kubectl version --short
Client Version: v1.20.3
Server Version: v1.19.6
```

**Comment by nicholastmosher** [comment] 2021-03-03 14:01
One potential solution to this is to create a pid-lockfile when the local cluster is created. This would allow a client to check for the lockfile and check if a process with that pid exists. If yes, then it can prevent the user from creating any new clusters.

**Comment by nicholastmosher** [comment] 2021-03-25 13:47
https://www.ysagade.nl/2018/06/24/creating-lockfiles/

**Comment by sehz** [comment] 2021-03-25 16:00
dupe of #666

**Closed by sehz** 2021-03-25 16:00 UTC
Labels: CLI, Installation, bug, trouble shooting
