### ISSUE TITLE
[Bug]: Fluvio client does not detect broken connection while consuming after machine suspend and resume

### ISSUE THREAD

**Issue by ajhunyady** [infinyon/fluvio#1514] opened 2021-08-26 22:55 UTC
I started a client instance to listen on a topic/partition

> fluvio consume fluvio-stars -k -B

[2021-08-26 19:12:15] 600
[2021-08-26 19:14:17] 600
[2021-08-26 19:16:18] 600
[2021-08-26 19:18:20] 600
[2021-08-26 19:20:22] 600
[2021-08-26 19:22:24] 600
[2021-08-26 19:24:25] 600
[2021-08-26 19:26:27] 600
[2021-08-26 19:28:29] 600

After a while I closed the laptop. When I returned, the connection looked alive... but soon realized that it does not receive traffic.

Expected behavior 

(the minimum)
 * Exit out of the loop of connection error and print the error: `Connection Error`

(better)
 * Try to reconnect, and give up after a certain number of retries.

**Comment by tjtelan** [comment] 2021-09-23 19:06
Caused by #770

**Comment by nacardin** [comment] 2021-09-24 19:13
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-6140c6361f93f200184da0bf/issues/infinyon/fluvio/1514?planning-poker) with ZenHub @morenol @nicholastmosher @sehz @simlay @tjtelan

**Comment by tjtelan** [comment] 2021-11-22 20:16
This should be approached as an automated test.

Start consume, simulate a network failure, verify reconnection and resuming consuming

**Comment by nacardin** [comment] 2021-11-30 19:31
I'll check behavior on Mac laptop on 0.9.13

**Comment by nacardin** [comment] 2021-11-30 20:53
On MacOS, this behavior is still present as of 0.9.13. Closing the laptop for 1 minutes is fine, consume is still alive. If I close the laptop for about 10 minutes, the consume command is still running, but is not showing new records.

**Comment by nacardin** [comment] 2021-12-02 19:11
Let's check netstat to see the state of the socket during this behavior

**Comment by morenol** [comment] 2021-12-03 23:16
After suspend and resume in linux:

```bash
$ sudo netstat  -ntpe4     | grep 900
tcp        0      0 192.168.1.105:57768     3.211.184.49:9003       ESTABLISHED 1000       146968     15068/fluvio        
tcp        0      0 192.168.1.105:38622     3.211.184.49:9005       ESTABLISHED 1000       144072     15068/fluvio        
```

**Comment by sehz** [comment] 2021-12-04 00:29
defering

**Closed** 2023-07-05 11:19 UTC
Labels: bug, no-issue-activity
