### ISSUE TITLE
Release workflow does not force push docker image

### ISSUE THREAD

**Issue by nacardin** [infinyon/fluvio#1516] opened 2021-08-27 00:04 UTC
`FORCE_RELEASE` is not having intended effect in `release_docker` job

**Comment by nicholastmosher** [comment] 2021-09-02 18:39
@nacardin can you assign this to a milestone when you have a chance?

**Comment by tjtelan** [comment] 2021-09-07 19:00
The problem is that while we check for `FORCE_RELEASE`, we do not actually perform the push on L144, unlike what we report.

https://github.com/infinyon/fluvio/blob/aa30e7eab255d995509be4b6fa0f8465120ba578/.github/workflows/release.yml#L143-L151

**Comment by digikata** [comment] 2024-03-22 00:32
outdated

**Closed by digikata** 2024-03-22 00:32 UTC
Labels: build-release, technical debt
