### ISSUE TITLE
CI should check for unused dependencies

### ISSUE THREAD

**Issue by nacardin** [infinyon/fluvio#415] opened 2020-10-22 22:07 UTC
Currently `cargo-udeps` detects the following unused dependencies:
```
`fluvio-cli v0.2.0 (/home/ubuntu/fluvio/src/cli)`
└─── dependencies
     ├─── "async-h1"
     ├─── "http-types"
     └─── "rpassword"
`fluvio-sc v0.2.0 (/home/ubuntu/fluvio/src/sc)`
└─── dependencies
     ├─── "toml"
     └─── "utils"
`fluvio-spu v0.1.0 (/home/ubuntu/fluvio/src/spu)`
└─── dependencies
     ├─── "serde_yaml"
     ├─── "toml"
     └─── "utils"
`fluvio-stream-dispatcher v0.2.0 (/home/ubuntu/fluvio/src/stream-dispatcher)`
└─── dev-dependencies
     └─── "flv-util"
`fluvio-stream-model v0.2.0 (/home/ubuntu/fluvio/src/stream-model)`
└─── dependencies
     └─── "fluvio-types"
`fluvio-system-util v0.1.0 (/home/ubuntu/fluvio/src/utils)`
└─── dependencies
     └─── "regex"
`fluvio-types v0.1.0 (/home/ubuntu/fluvio/src/types)`
└─── dependencies
     └─── "tracing"
`flv-test v1.0.1 (/home/ubuntu/fluvio/tests/runner)`
└─── dependencies
     ├─── "k8-client"
     └─── "k8-metadata-client"
```

**Comment by sehz** [comment] 2021-06-07 05:50
We should add this to CI as part of check?

**Comment by tjtelan** [comment] 2021-08-04 23:57
I just opened a PR, but I seem to have several errors that I can't reproduce locally.

Seems to be related to #1292 however, there doesn't seem to be an obvious reason for the compilation failure.

```
error: proc-macro derive panicked
  --> src/cluster/src/charts/location.rs:14:28
   |
14 | const SYS_CHART_DIR: Dir = include_dir!("../../k8-util/helm/pkg_sys");
   |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: message: "/home/runner/work/fluvio/fluvio/src/cluster/../../k8-util/helm/pkg_sys" doesn't exist
   = note: this error originates in the macro `include_dir` (in Nightly builds, run with -Z macro-backtrace for more info)

```

**Comment by morenol** [comment] 2021-08-05 00:04
I think that it was fixed in https://github.com/infinyon/fluvio/pull/1376 that was just merged recently, maybe a rebase should be enough

**Comment by nacardin** [comment] 2022-01-27 19:38
We can run this in separate workflow

**Closed** 2022-02-09 23:05 UTC
Labels: technical debt, CI
