### ISSUE TITLE
Installing cluster 2nd time result in crash

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#351] opened 2020-10-03 01:43 UTC
steps to reproduce:
(1) Install fluvio
(2) Install cluster from alpha release: 
```
fluvio cluster install --chart-version 0.6.0-latest --image-version 0.6.0-alpha.1
```
This is successful 
(3) Uninstall
```
$ fluvio cluster uninstall
```
(4) Trying to re-install
```
fluvio cluster install --chart-version 0.6.0-latest --image-version 0.6.0-alpha.1
Error: repository name (fluvio) already exists, please specify a different name
Exited with status code: 1
The application panicked (crashed).
Message:  internal error: entered unreachable code
Location: /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/flv-util-0.5.2/src/cmd.rs:92

Backtrace omitted.
Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

**Comment by sehz** [comment] 2020-10-03 01:49
work around is 
```
helm repo remove fluvio
```

**Comment by nicholastmosher** [comment] 2020-10-04 03:42
I believe I've figured out how to reproduce this. Suppose I had added a helm repo like this:

```
helm repo add fluvio https://infinyon.github.io
```

If I then try to create a repo by the same name _with a different address_, it will give me an error

```
helm repo add fluvio https://charts.fluvio.io
# Error exit code, causes fluvio to crash
```

However, if you re-run the `helm repo add` command using the exact same chart location, it will give you no problems.
I believe the reason we were seeing this is because we recently changed our chart repo from infinyon.github.io to charts.fluvio.io. I don't think that any newly-installed instances will experience this problem. However, I do agree that we should have more graceful error handling for non-zero exit status external commands. Right now any non-zero exit code panics.

I propose closing this issue and opening a new issue about external command error handling.

**Comment by sehz** [comment] 2020-10-04 03:52
So is there code still refer to old chart location?  I am using latest CLI.    I see 
```
>> helm version
>> helm list --filter ^fluvio-sys$ --output json
>> helm list --filter ^fluvio$ --output json
>> helm repo add fluvio https://charts.fluvio.io
Error: repository name (fluvio) already exists, please specify a different name
Exited with status code: 1
The application panicked (crashed).
Message:  internal error: entered unreachable code
Location: /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/flv-util-0.5.2/src/cmd.rs:92

Backtrace omitted.
```

And If tried manually:
```
helm repo add fluvio https://charts.fluvio.io
Error: repository name (fluvio) already exists, please specify a different name
```

I can reproduce the issue.  

So CLI should either remove existing repo or not add new if repo if doesn't exists

**Comment by nicholastmosher** [comment] 2020-10-04 04:01
What is the output of your `helm repo list`? If you have a repo called `fluvio` but it does not have the exact same URL that the installer is trying to use then it won't work. My guess is you will get output like

```
NAME    URL
fluvio  https://infinyon.github.io
```

If that's the case, try `helm repo remove fluvio` and try installing again

**Comment by sehz** [comment] 2020-10-04 04:08
```
 helm repo list
NAME    URL                     
fluvio  https://charts.fluvio.io
ubuntu@ip-172-31-20-82:~/fluvio$ 
```

this has been created by installer

**Comment by nicholastmosher** [comment] 2020-10-04 04:11
What do you get if you try to run 

```
helm repo remove fluvio
helm repo add fluvio https://charts.fluvio.io
helm repo add fluvio https://charts.fluvio.io
echo $?
```

Does helm give you a non-zero exit code?

**Comment by sehz** [comment] 2020-10-04 04:12
```
helm repo add fluvio https://charts.fluvio.io
"fluvio" has been added to your repositories
ubuntu@ip-172-31-20-82:~/fluvio$ helm repo add fluvio https://charts.fluvio.io
Error: repository name (fluvio) already exists, please specify a different name

**Comment by nicholastmosher** [comment] 2020-10-04 04:23
Weird. I wonder if this is a difference between helm versions or between helm behavior on different platforms. When I run that same series of commands it returns a 0 exit code.
Can you update to helm `3.3.4` and try that same thing?

**Comment by sehz** [comment] 2020-10-04 04:28
that fixed it!.   I will close the issue

**Comment by sehz** [comment] 2020-10-04 04:28
Actually, we should min helm to `3.3.4`

**Closed** 2020-10-04 05:16 UTC
Labels: CLI, Helm, Priority - Critical
