### ISSUE TITLE
Asymetric encoding in FluvioCodec

### ISSUE THREAD

**Issue by simlay** [infinyon/fluvio#1092] opened 2021-05-18 03:02 UTC
This is a twin issue to #1080.

The [encoding in `FluvioCodec`](https://github.com/infinyon/fluvio/blob/895662a348a2041ee961e2164073820cb77cb49c/src/protocol/fluvio-protocol-codec/src/codec.rs#L29-L84) isn't symmetric.

To reproduce this bug, add the following unit test or [append to `src/protocol/fluvio-protocol-codec/src/codec.rs`](https://github.com/infinyon/fluvio/blob/895662a348a2041ee961e2164073820cb77cb49c/src/protocol/fluvio-protocol-codec/src/codec.rs#L291):
```rust
#[cfg(test)]
mod encoder_test {
    use std::io::Error;
    use super::BytesMut;
    use super::Decoder;
    use super::Encoder;
    use super::FluvioCodec;

    #[test]
    fn test_encode_and_decode_fluvio_codec() -> Result<(), Error> {
        let bytes_from_tcp_logs = vec![0, 0, 0, 16, 0, 18, 0, 0, 0, 0, 0, 1, 0, 6, 102, 108, 117,
        118, 105, 111];
        let mut codec = FluvioCodec::new();

        let output = codec.decode(&mut BytesMut::from(bytes_from_tcp_logs.as_slice()))?;
        assert!(output.is_some());
        let output = output.unwrap();
        let mut encoded = BytesMut::new();
        let _ = codec.encode(output.freeze(), &mut encoded)?;
        //let encoded_bytes = encoded.to_vec();

        assert_eq!(bytes_from_tcp_logs, encoded.to_vec());

        Ok(())
    }
}
```

`cargo test` yields
```
failures:

---- codec::encoder_test::test_encode_and_decode_fluvio_codec stdout ----
thread 'codec::encoder_test::test_encode_and_decode_fluvio_codec' panicked at 'assertion failed: `(left == right)`
  left: `[0, 0, 0, 16, 0, 18, 0, 0, 0, 0, 0, 1, 0, 6, 102, 108, 117, 118, 105, 111]`,
 right: `[0, 18, 0, 0, 0, 0, 0, 1, 0, 6, 102, 108, 117, 118, 105, 111]`', src/protocol/fluvio-protocol-codec/src/codec.rs:314:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Hopefully this will fix some of the issues from #989. :crossed_fingers:

**Comment by morenol** [comment] 2021-05-18 03:59
I think that this is because `let _ = codec.encode(output.freeze(), &mut encoded)?;` is working with [Bytes](https://github.com/infinyon/fluvio/blob/895662a348a2041ee961e2164073820cb77cb49c/src/protocol/fluvio-protocol-codec/src/codec.rs#L76) instead of [FluvioCodecData](https://github.com/infinyon/fluvio/blob/895662a348a2041ee961e2164073820cb77cb49c/src/protocol/fluvio-protocol-codec/src/codec.rs#L87).
 
 That implementation with Bytes was kept in order to not produce breaking changes, maybe we should remove that?

**Comment by sehz** [comment] 2021-05-18 04:01
No, This seem be caused by: https://github.com/infinyon/fluvio/pull/989/files#diff-51b8697ad513de545576b213c6c7d698d2049d3305a3324ec86e98ea90a94910

**Comment by sehz** [comment] 2021-05-20 00:03
This was due to separate code for WebSocket.  This will be move to futures-io.  Closing

**Closed by sehz** 2021-05-20 00:03 UTC
Labels: API, bug, priority/blocked, protocol support
