### ISSUE TITLE
SmartStream aggregate  for version 0.3.0 doesn't work for current version 

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#1894] opened 2021-11-14 00:59 UTC
Steps to reproduce.

Deploy latest dev release of fluvio.
```
$ git checkout tags/v0.9.12 -b v9.12
$ make build_smartstreams
$ fluvio Topic create
```
Consume fails
```
$ fluvio consume test -B --aggregate  crates/fluvio-smartstream/examples/target/wasm32-unknown-unknown/release/fluvio_wasm_aggregate.wasm 

Consuming records from the beginning of topic 'test'
Consumer stream has closed
```

**Comment by morenol** [comment] 2021-11-18 14:58
So, the issue is that now we changed the output of the aggregate function to return SmartStreamAggregateOutput instead of SmartStreamOutput (it includes now the accumulator, in the new version of fluvio we expect to have the accumulator in the output so it fails decoding, I can change the smartengine to be backward compatible but if I do that the old error from aggregate(not be persistent across batches) is maintained for old versions

**Comment by nacardin** [comment] 2021-11-19 17:35
Closed by https://github.com/infinyon/fluvio/pull/1921

**Closed** 2021-11-20 04:13 UTC
Labels: bug, API, Priority/critical, regression, feature/smart_module
