### ISSUE TITLE
fluvio cluster startup instability in CD

### ISSUE THREAD

**Issue by tjtelan** [infinyon/fluvio#1480] opened 2021-08-20 19:47 UTC
In the `CD_Dev` workflow, the cross platform test fails due to a problem with the cluster startup.

```
Starting cluster
✅ ok: Kubernetes config is loadable
✅ ok: Supported helm version is installed
✅ ok: Fixed: Missing Fluvio system charts.
✅ ok: Previous fluvio installation not found
installing fluvio chart
Fluvio SC is up at: 172.18.0.2:32031
Error: 
   0: Fluvio cluster error
   1: Failed to install Fluvio on Kubernetes
   2: Fluvio client error
   3: Fluvio socket error
   4: Connection refused (os error 111)
```

**Comment by sehz** [comment] 2021-08-20 21:33
caused by #1453

**Comment by sehz** [comment] 2021-08-29 15:02
Upgrade test will be fixed in 0.9.6 since installer's instability is fixed in 0.9.5

**Comment by sehz** [comment] 2021-09-04 17:34
fixed

**Closed by sehz** 2021-09-04 17:34 UTC
Labels: Test, CD
