### ISSUE TITLE
[Bug]: Partition not found: <topic>-0

### ISSUE THREAD

**Issue by feamcor** [infinyon/fluvio#660] opened 2021-01-10 01:05 UTC
**What happened**
Following the tutorial ["Hello, World! 🎉" in Rust](https://nightly.fluvio.io/tutorials/rust/hello-world/), when running `cargo run -- produce` or `cargo run -- consume`, the following error is returned:
> Got error: Partition not found: hello-fluvio-0

**Expected behavior**
Producing "Hello, Fluvio!" into the `hello-fluvio` topic or consuming and displaying its content.

**Describe the setup**
- Fluvio (local) 
> Fluvio CLI      : 0.6.0-rc.3
> Fluvio Platform : 0.6.0-rc.3
> Git Commit      : 769ba7a8b3f72230abf753c91425ed315e18a58c
> OS Details      : Linux 5.4.0-1032-azure x86_64 GNU/Linux
> Rustc Version   : 1.48.0 (7eac88a 2020-11-16)
- Minikube
> minikube version: v1.16.0
> commit: 9f1e482427589ff8451c4723b6ba53bb9742fbb1
- Kubernetes
> Client Version: v1.19.3
> Server Version: v1.19.3
- Operating System
> Ubuntu 20.04 on WSL2 on Windows10 Pro 20H2
- Rust
> stable-x86_64-unknown-linux-gnu
> rustc 1.49.0 (e1884a8e3 2020-12-29)

**How to reproduce it (as minimally and precisely as possible)**
`cargo run -- produce`
`cargo run -- consume`

**Log output**
``` bash
❯ cd hello-fluvio

❯ cargo clean

❯ cargo build
   Compiling proc-macro2 v1.0.24
   Compiling unicode-xid v0.2.1
   Compiling syn v1.0.58
   Compiling libc v0.2.82
   Compiling log v0.4.11
   Compiling cfg-if v0.1.10
   Compiling pin-project-lite v0.2.3
   Compiling futures-core v0.3.9
   Compiling memchr v2.3.4
   Compiling autocfg v1.0.1
   Compiling lazy_static v1.4.0
   Compiling futures-io v0.3.9
   Compiling once_cell v1.5.2
   Compiling cfg-if v1.0.0
   Compiling cache-padded v1.1.1
   Compiling waker-fn v1.1.0
   Compiling parking v2.0.0
   Compiling fastrand v1.4.0
   Compiling event-listener v2.5.1
   Compiling cc v1.0.66
   Compiling pkg-config v0.3.19
   Compiling vec-arena v1.0.0
   Compiling async-task v4.0.3
   Compiling bitflags v1.2.1
   Compiling matches v0.1.8
   Compiling tinyvec_macros v0.1.0
   Compiling atomic-waker v1.0.0
   Compiling openssl v0.10.32
   Compiling foreign-types-shared v0.1.1
   Compiling bytes v0.5.6
   Compiling slab v0.4.2
   Compiling pin-utils v0.1.0
   Compiling percent-encoding v2.1.0
   Compiling native-tls v0.2.7
   Compiling futures-sink v0.3.9
   Compiling nix v0.17.0
   Compiling openssl-probe v0.1.2
   Compiling proc-macro-hack v0.5.19
   Compiling pin-project-lite v0.1.11
   Compiling proc-macro-nested v0.1.6
   Compiling void v1.0.2
   Compiling ucd-trie v0.1.3
   Compiling maybe-uninit v2.0.0
   Compiling serde_derive v1.0.118
   Compiling crc32c v0.5.0
   Compiling serde v1.0.118
   Compiling stable_deref_trait v1.2.0
   Compiling pin-project-internal v0.4.27
   Compiling ryu v1.0.5
   Compiling static_assertions v1.1.0
   Compiling serde_json v1.0.61
   Compiling itoa v0.4.7
   Compiling base64 v0.12.3
   Compiling tracing-core v0.1.17
   Compiling futures-task v0.3.9
   Compiling concurrent-queue v1.2.2
   Compiling async-mutex v1.4.0
   Compiling unicode-bidi v0.3.4
   Compiling crossbeam-utils v0.8.1
   Compiling tinyvec v1.1.0
   Compiling foreign-types v0.3.2
   Compiling form_urlencoded v1.0.0
   Compiling pest v2.1.3
   Compiling owning_ref v0.3.3
   Compiling async-rwlock v1.3.0
   Compiling async-channel v1.5.1
   Compiling openssl-sys v0.9.60
   Compiling kv-log-macro v1.0.7
   Compiling fluvio-protocol-core v0.1.0
   Compiling futures-lite v1.11.3
   Compiling content_inspector v0.2.4
   Compiling quote v1.0.8
   Compiling unicode-normalization v0.1.16
   Compiling smallvec v0.6.14
   Compiling semver-parser v0.10.2
   Compiling nb-connect v1.0.2
   Compiling polling v2.0.2
   Compiling signal-hook-registry v1.3.0
   Compiling num_cpus v1.13.0
   Compiling rand v0.4.6
   Compiling dirs v1.0.5
   Compiling async-executor v1.4.0
   Compiling blocking v1.0.2
   Compiling semver v0.11.0
   Compiling idna v0.2.0
   Compiling async-io v1.3.1
   Compiling signal-hook v0.1.17
   Compiling parking_lot_core v0.2.14
   Compiling url v2.2.0
   Compiling parking_lot v0.4.8
   Compiling async-global-executor v1.4.3
   Compiling async-process v1.0.1
   Compiling async-net v1.5.0
   Compiling chashmap v2.2.2
   Compiling async-std v1.8.0
   Compiling tracing-attributes v0.1.11
   Compiling thiserror-impl v1.0.23
   Compiling tokio-macros v0.2.6
   Compiling pin-project-internal v1.0.4
   Compiling fluvio-protocol-derive v0.1.1
   Compiling async-trait v0.1.42
   Compiling futures-macro v0.3.9
   Compiling tokio v0.2.24
   Compiling futures-util v0.3.9
   Compiling thiserror v1.0.23
   Compiling tracing v0.1.22
   Compiling async-native-tls v0.3.3
   Compiling tokio-util v0.3.1
   Compiling flv-util v0.5.2
   Compiling fluvio-types v0.2.1
   Compiling fluvio-stream-model v0.3.1
   Compiling pin-project v1.0.4
   Compiling fluvio-protocol-api v0.1.1
   Compiling fluvio-protocol-codec v0.1.1
   Compiling fluvio-future v0.1.13
   Compiling fluvio-protocol v0.2.1
   Compiling pin-project v0.4.27
   Compiling tracing-futures v0.2.4
   Compiling fluvio-dataplane-protocol v0.1.4
   Compiling fluvio-socket v0.4.3
   Compiling fluvio-controlplane-metadata v0.3.1
   Compiling fluvio-spu-schema v0.2.0
   Compiling toml v0.5.8
   Compiling fluvio-sc-schema v0.3.1
   Compiling fluvio v0.3.3
   Compiling hello-fluvio v0.1.0 (/home/feamcor/hello-fluvio)
    Finished dev [unoptimized + debuginfo] target(s) in 2m 04s
hello-fluvio on master [?] is 📦 v0.1.0 via 🦀 v1.49.0 took 2m5s

❯ fluvio topic list
 NAME          TYPE      PARTITIONS  REPLICAS  IGNORE-RACK  STATUS                   REASON
 hello-fluvio  computed      1          1                   resolution::provisioned

❯ fluvio consume hello-fluvio -B
"Hello Fluvio #1"
"Hello Fluvio #2"
"Hello Fluvio #3"
"Hello Fluvio #4"
"Hello Fluvio #5"
^C

❯ cargo run -- produce
    Finished dev [unoptimized + debuginfo] target(s) in 0.13s
     Running `target/debug/hello-fluvio produce`
producer created
Got error: Partition not found: hello-fluvio-0

❯ cargo run -- produce "Hello Fluvio #6"
    Finished dev [unoptimized + debuginfo] target(s) in 0.13s
     Running `target/debug/hello-fluvio produce 'Hello Fluvio #6'`
producer created
Got error: Partition not found: hello-fluvio-0

❯ cargo run -- consume
    Finished dev [unoptimized + debuginfo] target(s) in 0.13s
     Running `target/debug/hello-fluvio consume`
consumer created
Got error: Partition not found: hello-fluvio-0
```

**Environment (please complete the following information):**
- See setup info above.

**Additional context**
- Cargo.toml
``` toml
[package]
name = "hello-fluvio"
version = "0.1.0"
authors = ["***** ****** <*******@*****.***>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fluvio = "0.3.3"
async-std = "1.0.0"
```

- main.rs
``` rust
use fluvio::{Offset, FluvioError};
use async_std::stream::StreamExt;
use async_std::task::block_on;

fn main() {
    let args: Vec<String> = std::env::args().collect();
    let args_slice: Vec<&str> = args.iter().map(|s| &**s).collect();

    let result = match &*args_slice {
        [_, "produce"] => {
            block_on(produce("Hello, Fluvio!"))
        },

        [_, "produce", rest @ ..] => {
            let message = rest.join(" ");
            block_on(produce(&message))
        },

        [_, "consume"] => {
            block_on(consume())
        },

        _ => {
            eprintln!("Usage: hello-fluvio <produce|consume> [message]");
            return;
        },
    };

    if let Err(err) = result {
        eprintln!("Got error: {}", err);
    }
}

async fn produce(message: &str) -> Result<(), FluvioError> {
    let producer = fluvio::producer("hello-fluvio").await?;
    eprintln!("producer created");
    producer.send_record(message, 0).await?;
    eprintln!("message sent");
    Ok(())
}

async fn consume() -> Result<(), FluvioError> {
    let consumer = fluvio::consumer("hello-fluvio", 0).await?;
    eprintln!("consumer created");
    let mut stream = consumer.stream(Offset::beginning()).await?;
    eprintln!("stream created");
    while let Some(Ok(record)) = stream.next().await {
        eprintln!("record fetched");
        if let Some(bytes) = record.try_into_bytes() {
            let string = String::from_utf8_lossy(&bytes);
            println!("Got record: {}", string);
        }
    }

    Ok(())
}
```

**Comment by nicholastmosher** [comment] 2021-01-11 15:31
Hi @feamcor, thanks for the bug report! I believe this is caused by a bug that we have seen in `0.6.0-rc.3` which causes the `Partition not found` error that you are seeing. I just tried running through the tutorial with the latest version, `0.6.0-rc.5` and it seems to work as expected.

Could you see if this is resolved for you as well? You can update to the latest version of Fluvio using `fluvio update`. I will update the documentation with the new minimum required version numbers that make this work.

**Comment by nicholastmosher** [comment] 2021-01-11 19:06
We're going to go ahead and close this, @feamcor if you are still experiencing this problem feel free to re-open, or if there are other problems of course feel free to open another issue! Thanks

**Closed by nicholastmosher** 2021-01-11 19:06 UTC
Labels: bug, documentation

**Comment by feamcor** [comment] 2021-01-12 01:14
Yes, it worked after:
- fluvio update
- fluvio cluster delete
- fluvio cluster check
- fluvio cluster start
- Changed fluvio dependency to 0.3.4.
Thanks.
